apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-register
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-register
  template:
    metadata:
      labels:
        app: front-register
    spec:
      containers:
      - name: front-register
        stdin: true
        tty: true
        image: satoshisystems.azurecr.io/demo/front-register
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: front-register-service
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: front-register
  type: LoadBalancer