apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: tls-secret-prd-backend
  namespace: ingress-basic
spec:
  secretName: tls-secret-prd-backend
  dnsNames:
    - backend.eastus.cloudapp.azure.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - backend.eastus.cloudapp.azure.com
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer